Repository AmirSavand/royale-plus, pull requests merged in 2018-03, with the labels that each got.

#26 Google Analytics Fix
  basement/static/app.js
  basement/static/lib/angular-google-analytics/angular-google-analytics.js
  basement/views.py
  templates/index.html
Labels: bug

#27 Fix dep
  basement/static/app.js
Labels: bug

#28 Fix page for GA
  basement/static/app.js
  royale_plus/settings.py
Labels: bug

#23 Initial activity app
  account/__init__.py
  account/admin.py
  account/apps.py
  account/migrations/0002_auto_20180310_1624.py
  account/migrations/0003_auto_20180311_1643.py
  account/models.py
  account/signals.py
  activity/__init__.py
  activity/admin.py
  activity/apps.py
  activity/migrations/0001_initial.py
  activity/migrations/0002_activity_issued.py
  activity/migrations/0003_auto_20180311_1643.py
  activity/migrations/__init__.py
  activity/models.py
  activity/tests.py
  activity/views.py
  api/serializers.py
  api/urls.py
  api/views.py
  basement/static/app_constant.js
  basement/static/app_routes.js
  basement/static/assets/css/main.css
  basement/static/components/account/account.js
  basement/static/components/account/auth/auth.js
  basement/static/components/account/auth/auth_interceptor.js
  basement/static/components/account/settings/settings_controller.js
  basement/static/components/activity/activity.js
  basement/static/components/activity/activity_include.html
  basement/static/components/api/api.js
  basement/static/components/card/card_include.html
  basement/static/components/deck/deck.html
  basement/static/components/deck/deck.js
  basement/static/components/deck/deck_list/deck_list.html
  basement/static/components/deck/deck_new/deck_new.html
  basement/static/components/deck/deck_new/deck_new_controller.js
  basement/static/components/home/home.html
  basement/static/components/home/home_controller.js
  basement/static/components/main/main_controller.js
  basement/static/components/user/user.html
  deck/__init__.py
  deck/admin.py
  deck/apps.py
  deck/migrations/0002_auto_20180310_1624.py
  deck/migrations/0003_auto_20180311_1643.py
  deck/models.py
  deck/signals.py
  royale_plus/settings.py
  templates/index.html
Labels: enhancement, feature

#56 Add user activities to profile
  api/views.py
  basement/static/components/user/user.html
  basement/static/components/user/user_controller.js
Labels: ready

#61 Deck comments
  basement/static/components/deck/deck.html
  basement/static/components/deck/deck_controller.js
  basement/static/components/home/home.html
  basement/static/components/user/user.html
Labels: ready

#63 Don't comment if user is not authenticated
  basement/static/components/comment/comment.js
Labels: ready

#57 Remove disqus use comments
  api/views.py
  basement/static/app.js
  basement/static/app_constant.js
  basement/static/assets/css/main.css
  basement/static/assets/css/shorties.css
  basement/static/components/api/api.js
  basement/static/components/comment/comment.js
  basement/static/components/comment/comment_form_include.html
  basement/static/components/comment/comment_include.html
  basement/static/components/deck/deck.html
  basement/static/components/deck/deck.js
  basement/static/components/deck/deck_controller.js
  basement/static/components/deck/deck_list/deck_list.html
  basement/static/components/deck/deck_new/deck_new_controller.js
  basement/static/components/home/home.html
  basement/static/components/home/home_controller.js
  basement/static/components/user/user.html
  basement/static/components/user/user_controller.js
  basement/static/lib/angular-disqus/angular-disqus.js
  templates/index.html
Labels: ready

#55 Comment
  api/serializers.py
  api/urls.py
  api/views.py
  basement/static/app.js
  basement/static/app_constant.js
  basement/static/assets/css/main.css
  basement/static/assets/css/shorties.css
  basement/static/components/api/api.js
  basement/static/components/comment/comment.js
  basement/static/components/comment/comment_form_include.html
  basement/static/components/comment/comment_include.html
  basement/static/components/deck/deck.html
  basement/static/components/deck/deck.js
  basement/static/components/deck/deck_controller.js
  basement/static/components/deck/deck_list/deck_list.html
  basement/static/components/deck/deck_new/deck_new_controller.js
  basement/static/components/home/home.html
  basement/static/components/home/home_controller.js
  basement/static/components/user/user.html
  basement/static/components/user/user_controller.js
  basement/static/lib/angular-disqus/angular-disqus.js
  comment/__init__.py
  comment/admin.py
  comment/apps.py
  comment/migrations/0001_initial.py
  comment/migrations/__init__.py
  comment/models.py
  royale_plus/settings.py
  templates/index.html
Labels: ready

#66 Remove auth requirement for new build route
  basement/static/app_routes.js
  basement/static/components/deck/deck_new/deck_new.html
  basement/static/components/deck/deck_new/deck_new_controller.js
Labels: ready

#68 Check if atleast one mode is selected
  basement/static/components/deck/deck_new/deck_new_controller.js
Labels: ready

#69 Improve deck all modes
  deck/models.py
Labels: ready

#70 Is profile completed
  account/models.py
  api/serializers.py
  basement/static/components/main/main.html
Labels: ready

#73 Fix loadmore arrow
  basement/static/components/common/pagination/pagination_include.html
Labels: ready

#77 Navbar account instance
  basement/static/components/main/main.html
  basement/static/components/main/main_controller.js
Labels: ready

#74 Use follow system
  basement/static/components/account/account.js
  basement/static/components/api/api.js
  basement/static/components/home/home.html
  basement/static/components/main/main.html
  basement/static/components/main/main_controller.js
  basement/static/components/user/user.html
  basement/static/components/user/user_controller.js
  royale_plus/settings.py
Labels: ready

#72 Add Follow
  account/admin.py
  account/migrations/0004_auto_20180317_1528.py
  account/models.py
  api/serializers.py
  api/urls.py
  api/views.py
  basement/static/components/account/account.js
  basement/static/components/api/api.js
  basement/static/components/home/home.html
  basement/static/components/main/main.html
  basement/static/components/main/main_controller.js
  basement/static/components/user/user.html
  basement/static/components/user/user_controller.js
  royale_plus/settings.py
Labels: ready

#78 Users modal
  api/serializers.py
  basement/static/components/account/account.js
  basement/static/components/account/user_include.html
  basement/static/components/account/user_list/user_list.html
  basement/static/components/common/common.js
  basement/static/components/home/home.html
  basement/static/components/user/user.html
  basement/static/components/user/user_controller.js
Labels: in progress

#81 Signin account instance
  basement/static/components/account/auth/auth.js
  basement/static/components/main/main_controller.js
  basement/static/components/user/user_controller.js
Labels: ready

#82 Use django filters
  api/serializers.py
  api/views.py
  basement/static/app_routes.js
  basement/static/components/account/account.js
  basement/static/components/card/card.html
  basement/static/components/card/card.js
  basement/static/components/deck/deck_list/deck_list_controller.js
  basement/static/components/deck/deck_new/deck_new_controller.js
  basement/static/components/user/user_controller.js
  royale_plus/settings.py
Labels: ready

#85 Deck list filter
  basement/static/components/deck/deck_list/deck_list.html
  basement/static/components/deck/deck_list/deck_list_controller.js
Labels: ready

#84 Unit tests
  account/tests.py
  api/tests.py
  api/urls.py
  basement/tests.py
  deck/tests.py
Labels: Test, in progress

#90 Remove decks
  basement/static/components/deck/deck.js
  basement/static/components/deck/deck_list/deck_list.html
Labels: ready

#94 Improve deck list ui
  basement/static/components/common/nothing/nothing_include.html
  basement/static/components/deck/deck_list/deck_list.html
  basement/static/components/deck/deck_list/deck_list_controller.js
Labels: ready

#93 Add comment activity
  comment/__init__.py
  comment/apps.py
  comment/recivers.py
Labels: ready

#92 Add padding for load more
  basement/static/components/common/pagination/pagination_include.html
Labels: ready

#96 Improve activity
  basement/static/components/activity/activity.js
  basement/static/components/activity/activity_include.html
  basement/static/components/common/nothing/nothing_include.html
  royale_plus/settings.py
Labels: ready

#99 Auto follow user
  account/signals.py
  royale_plus/settings.py
Labels: ready

#100 Fix activity button
  basement/static/components/activity/activity.js
  basement/static/components/activity/activity_include.html
Labels: ready

#101 Load cards when no localstorage
  basement/static/components/deck/deck_controller.js
  basement/static/components/deck/deck_list/deck_list_controller.js
Labels: ready

#107 Info modal for tournament
  basement/static/assets/css/mobile.css
  basement/static/components/tournament/tournament_info.html
  basement/static/components/tournament/tournament_list/tournament_list.html
  basement/static/components/tournament/tournament_list/tournament_list_controller.js
  basement/static/components/tournament/tournament_new/tournament_new.html
  basement/static/components/tournament/tournament_new/tournament_new_controller.js
Labels: ready

#109 Handle tournament user selection error
  basement/static/components/tournament/tournament_new/tournament_new_controller.js
Labels: ready

#110 Redirect user on tournament creation
  basement/static/components/tournament/tournament_controller.js
  basement/static/components/tournament/tournament_new/tournament_new_controller.js
Labels: ready

#111 A button to show all avatars at settings view
  basement/static/components/account/settings/settings.html
  basement/static/components/account/settings/settings_controller.js
Labels: ready

#112 Fix user picture field
  account/migrations/0006_remove_user_picture.py
  account/migrations/0007_user_picture.py
Labels: ready
